export const MockImages = {
  'Latest Products': [
    {
      id: '1',
      image:
        'https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=398&q=80',
    },
    {
      id: '2',
      image:
        'https://images.unsplash.com/photo-1587303876752-91efb6315dcc?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=435&q=80',
    },
    {
      id: '3',
      image:
        'https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=387&q=80',
    },
    {
      id: '4',
      image:
        'https://images.unsplash.com/photo-1611930022073-b7a4ba5fcccd?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1374&q=80',
    },
    {
      id: '5',
      image:
        'https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=398&q=80',
    },
    {
      id: '6',
      image:
        'https://images.unsplash.com/photo-1587303876752-91efb6315dcc?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=435&q=80',
    },
    {
      id: '7',
      image:
        'https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=387&q=80',
    },
    {
      id: '8',
      image:
        'https://images.unsplash.com/photo-1611930022073-b7a4ba5fcccd?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1374&q=80',
    },
  ],
  'Most Popular Products': [
    {
      id: '9',
      image:
        'https://images.unsplash.com/photo-1511556820780-d912e42b4980?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=387&q=80',
    },
    {
      id: '10',
      image:
        'https://images.unsplash.com/photo-1617005082133-548c4dd27f35?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=764&q=80',
    },
    {
      id: '11',
      image:
        'https://images.unsplash.com/photo-1576087503901-b2a3e3b66672?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=687&q=80',
    },
    {
      id: '12',
      image:
        'https://images.unsplash.com/photo-1575330933415-cea1e7ce53eb?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=687&q=80',
    },
  ],
  'Recently Viewed Products': [
    {
      id: '13',
      image:
        'https://images.unsplash.com/photo-1619153709175-64db4b9f5ed5?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=764&q=80',
    },
    {
      id: '14',
      image:
        'https://images.unsplash.com/photo-1584949514123-474cfa705dfe?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=687&q=80',
    },
    {
      id: '15',
      image:
        'https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=398&q=80',
    },
    {
      id: '16',
      image:
        'https://images.unsplash.com/photo-1617005082133-548c4dd27f35?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=764&q=80',
    },
  ],
};

export const MockProduct = {
  name: 'Contemporary wallpaper',
  desciption:
    'The collection Wallpaper On Demand N.O.W. Edizioni, offers tailor-made wallpapers. Thanks to technical printing and high-quality materials, we realize decorations declined in several color variations, overcoming the modular repetitions. A solution of interior design that satisfy the desires of most demanding customers.',
  style: 'contemporary',
  seller: 'N.O.W. Edizioni',
  seller_country: 'italy',
  seller_responseTime: 48, // average in hours
  review_rating: 5,
  review_participants: 100,
  motif: ['panoramic', 'geometric'],
  appearance: ['fabric look'],
  options: [
    'printed',
    'washable',
    'fire-retardant',
    'custom',
    'water-repellent',
    'acoustic',
    'abrasion-resistant',
  ],
  room: [
    'living rooms',
    'bedrooms',
    'dining rooms',
    'offices',
    "girl's room",
    "boy's room",
    "teenager's room",
    'bathrooms',
    'kitchens',
    'outdoor use',
  ],
  designer: 'Pietro Gaeta',
  width: '124 cm (49 in)',
  images_url: [
    'https://img.archiexpo.com/images_ae/photo-g/148145-17650768.webp',
    'https://img.archiexpo.com/images_ae/photo-g/148145-17650769.webp',
    'https://img.archiexpo.com/images_ae/photo-g/148145-17650770.webp',
    'https://img.archiexpo.com/images_ae/photo-g/148145-17650771.webp',
    'https://img.archiexpo.com/images_ae/photo-g/148145-17650782.webp',
  ],
};

export const manyImages = () => {
  let arr = [];
  for (let index = 0; index < 2; index++) {
    arr = [...arr, ...MockImages['Latest Products']];
  }

  for (
    let index = 0;
    index < MockImages['Latest Products'].length / 4;
    index++
  ) {
    console.log(MockImages['Latest Products'].slice(index, index + 4));
  }

  return arr;
};

export const countries = {
  unknown: 'xx',
  andorra: 'ad',
  'united arb eimarates': 'ae',
  afghanista: 'af',
  'antigua ad Barbuda': 'ag',
  anguilla: 'ai',
  albania: 'al',
  armenia: 'am',
  angola: 'ao',
  antartica: 'aq',
  argentina: 'ar',
  'american amoa': 'as',
  austria: 'at',
  australia: 'au',
  italy: 'it',
  // tbc: "aw",
  // tbc: "ax",
  // tbc: "az",
  // tbc: "ba",
  // tbc: "bb",
  // tbc: "bd",
  // tbc: "be",
  // tbc: "bf",
  // tbc: "bg",
  // tbc: "bh",
  // tbc: "bi",
  // tbc: "bj",
  // tbc: "bl",
  // tbc: "bm",
  // tbc: "bn",
  // tbc: "bo",
  // tbc: "bq",
  // tbc: "br",
  // tbc: "bs",
  // tbc: "bt",
  // tbc: "bv",
  // tbc: "bw",
  // tbc: "by",
  // tbc: "bz",
  // tbc: "ca",
  // tbc: "cc",
  // tbc: "cd",
  // tbc: "cf",
  // tbc: "cg",
  // tbc: "ch",
  // tbc: "ci",
  // tbc: "ck",
  // tbc: "cl",
  // tbc: "cm",
  // tbc: "cn",
  // tbc: "co",
  // tbc: "cr",
  // tbc: "cu",
  // tbc: "cv",
  // tbc: "cw",
  // tbc: "cx",
  // tbc: "cy",
  // tbc: "cz",
  // tbc: "de",
  // tbc: "dj",
  // tbc: "dk",
  // tbc: "dm",
  // tbc: "do",
  // tbc: "dz",
  // tbc: "ec",
  // tbc: "ee",
  // tbc: "eg",
  // tbc: "eh",
  // tbc: "er",
  // tbc: "es",
  // tbc: "et",
  // tbc: "fi",
  // tbc: "fj",
  // tbc: "fk",
  // tbc: "fm",
  // tbc: "fo",
  // tbc: "fr",
  // tbc: "ga",
  // tbc: "gb",
  // tbc: "gd",
  // tbc: "ge",
  // tbc: "gf",
  // tbc: "gg",
  // tbc: "gh",
  // tbc: "gi",
  // tbc: "gl",
  // tbc: "gm",
  // tbc: "gn",
  // tbc: "gp",
  // tbc: "gq",
  // tbc: "gr",
  // tbc: "gs",
  // tbc: "gt",
  // tbc: "gu",
  // tbc: "gw",
  // tbc: "gy",
  // tbc: "hk",
  // tbc: "hm",
  // tbc: "hn",
  // tbc: "hr",
  // tbc: "ht",
  // tbc: "hu",
  // tbc: "id",
  // tbc: "ie",
  // tbc: "il",
  // tbc: "im",
  // tbc: "in",
  // tbc: "io",
  // tbc: "iq",
  // tbc: "ir",
  // tbc: "is",
  // tbc: "je",
  // tbc: "jm",
  // tbc: "jo",
  // tbc: "jp",
  // tbc: "ke",
  // tbc: "kg",
  // tbc: "kh",
  // tbc: "ki",
  // tbc: "km",
  // tbc: "kn",
  // tbc: "kp",
  // tbc: "kr",
  // tbc: "kw",
  // tbc: "ky",
  // tbc: "kz",
  // tbc: "la",
  // tbc: "lb",
  // tbc: "lc",
  // tbc: "li",
  // tbc: "lk",
  // tbc: "lr",
  // tbc: "ls",
  // tbc: "lt",
  // tbc: "lu",
  // tbc: "lv",
  // tbc: "ly",
  // tbc: "ma",
  // tbc: "mc",
  // tbc: "md",
  // tbc: "me",
  // tbc: "mf",
  // tbc: "mg",
  // tbc: "mh",
  // tbc: "mk",
  // tbc: "ml",
  // tbc: "mm",
  // tbc: "mn",
  // tbc: "mo",
  // tbc: "mp",
  // tbc: "mq",
  // tbc: "mr",
  // tbc: "ms",
  // tbc: "mt",
  // tbc: "mu",
  // tbc: "mv",
  // tbc: "mw",
  // tbc: "mx",
  // tbc: "my",
  // tbc: "mz",
  // tbc: "na",
  // tbc: "nc",
  // tbc: "ne",
  // tbc: "nf",
  // tbc: "ng",
  // tbc: "ni",
  // tbc: "nl",
  // tbc: "no",
  // tbc: "np",
  // tbc: "nr",
  // tbc: "nu",
  // tbc: "nz",
  // tbc: "om",
  // tbc: "pa",
  // tbc: "pe",
  // tbc: "pf",
  // tbc: "pg",
  // tbc: "ph",
  // tbc: "pk",
  // tbc: "pl",
  // tbc: "pm",
  // tbc: "pn",
  // tbc: "pr",
  // tbc: "ps",
  // tbc: "pt",
  // tbc: "pw",
  // tbc: "py",
  // tbc: "qa",
  // tbc: "re",
  // tbc: "ro",
  // tbc: "rs",
  // tbc: "ru",
  // tbc: "rw",
  // tbc: "sa",
  // tbc: "sb",
  // tbc: "sc",
  // tbc: "sd",
  // tbc: "se",
  // tbc: "sg",
  // tbc: "sh",
  // tbc: "si",
  // tbc: "sj",
  // tbc: "sk",
  // tbc: "sl",
  // tbc: "sm",
  // tbc: "sn",
  // tbc: "so",
  // tbc: "sr",
  // tbc: "ss",
  // tbc: "st",
  // tbc: "sv",
  // tbc: "sx",
  // tbc: "sy",
  // tbc: "sz",
  // tbc: "tc",
  // tbc: "td",
  // tbc: "tf",
  // tbc: "tg",
  // tbc: "th",
  // tbc: "tj",
  // tbc: "tk",
  // tbc: "tl",
  // tbc: "tm",
  // tbc: "tn",
  // tbc: "to",
  // tbc: "tr",
  // tbc: "tt",
  // tbc: "tv",
  // tbc: "tw",
  // tbc: "tz",
  // tbc: "ua",
  // tbc: "ug",
  // tbc: "um",
  // tbc: "us",
  // tbc: "uy",
  // tbc: "uz",
  // tbc: "va",
  // tbc: "vc",
  // tbc: "ve",
  // tbc: "vg",
  // tbc: "vi",
  // tbc: "vn",
  // tbc: "vu",
  // tbc: "wf",
  // tbc: "ws",
  // tbc: "ye",
  // tbc: "yt",
  // tbc: "za",
  // tbc: "zm",
  // tbc: "zw",
};
